### PR TITLE
Fix multiple output crafting.

### PR DESCRIPTION
**Pull request by good777LUCKY**
It will fix multiple output crafting like cake (by Extollite)

### CODE REVIEW

**Comment by joserobjr** [comment]
Which crafting was broken?

**Comment by good777LUCKY** [comment]
Probably it was cake

**Comment by good777LUCKY** [comment]
https://github.com/NukkitX/Nukkit/issues/1451

**Comment by zombihunterbonn** [comment]
When do the piston functions come? 
@joserobjr

**Pull request merged**
