### PR TITLE
Migrating Honeycomb Block to Nukkit 2.0

### PR DESCRIPTION
**Pull request by LoboMetalurgico**

### CODE REVIEW

**Comment by joserobjr** [comment]
Depends on NukkitX#1128 to work.

**Comment by joserobjr** [comment]
As a workaround, adds this to the server plugin folder:
https://github.com/GameModsBR/Workaround-NukkitX-1128/releases/tag/0.0.1

**Comment by LoboMetalurgico** [comment]
Thank you for making this plugin! Now, I will declare that this pull is ready for analysis!

**Comment by Gabriel8579** [comment]
Can you rename your branch to use this pattern?
`v2.0/(block/item/entity/whatever)/(block-name)/(what-you-are-doing)`

**Comment by Gabriel8579** [comment]
Test result: success

**Comment by joserobjr** [comment]
Awaiting Nukkit for diplomatic reasons.

**Comment by LoboMetalurgico** [comment]
Ok!

**Pull request merged**
