### PR TITLE
Updates the project files based on the master branch

### PR DESCRIPTION
**Pull request by joserobjr**
Changes the project name to PowerNukkit, adds a README, removes the test badge and changes the build status badge to one generated by GitHub actions (will only show a status after this branch is merged, theoretically)

### CODE REVIEW

**Comment by joserobjr** [comment]
That's what I changed. It's showing correctly here: https://github.com/GameModsBR/PowerNukkit/tree/v2.0/powernukkit/build-status

image

Can you confirm?

**Comment by joserobjr** [comment]
The "no status" thing should change when the branch gets merged, it's there because there's no build with that name in the `2.0-migration` branch yet: https://github.com/GameModsBR/PowerNukkit/actions

**Comment by Gabriel8579** [comment]
> The "no status" thing should change when the branch gets merged, it's there because there's no build with that name in the `2.0-migration` branch yet: https://github.com/GameModsBR/PowerNukkit/actions

My fault, I was looking at the wrong branch ...

**Comment by joserobjr** [comment]
Alright, so I'm merging. Thank you 👍

**Pull request merged**
