### PR TITLE
[2.0] Migrates the Wither Rose Block 

### PR DESCRIPTION
**Pull request by Gabriel8579**
- [x] Living entities (except players) only take damage when there is a player very close

### CODE REVIEW

**Comment by Gabriel8579** [comment]
Living entities (except players) only take damage when there is a player very close. Possible fix at #187

**Comment by RORIdev** [comment]
> Living entities (except players) only take damage when there is a player very close. Possible fix at #187 

Is this still a thing? If so ill try to find a fix for that.

**Comment by Gabriel8579** [comment]
> > Living entities (except players) only take damage when there is a player very close. Possible fix at #187
> 
> Is this still a thing? If so ill try to find a fix for that.

I tested it recently, it occurs but I found a solution, waiting for this merge to be performed to make the correction due to countless conflicts

**Comment by Gabriel8579** [comment]
it will be handled at #280

**Pull request closed without merging**
