### PR TITLE
Migration of Kelp

### PR DESCRIPTION
**Pull request by RORIdev**
There is a lot of things to be done, the draft pr is here just for documentation purposes.

- [x] Can't break it in survivle.

### CODE REVIEW

**Comment by RORIdev** [comment]
As of [6603515](https://github.com/GameModsBR/PowerNukkit/pull/160/commits/660351585fa2931ef79fc5994337aae9fab64da2) : 
- [ ] Placing of kelp block was broken, as of `layerOneBlock` being air, due to a lack of waterlogging.

**Comment by joserobjr** [comment]
Depends on NukkitX#1128

As a workaround, adds this to the server plugin folder:
https://github.com/GameModsBR/Workaround-NukkitX-1128/releases/tag/0.0.1

**Comment by joserobjr** [comment]
Dependency is resolved, I'm going to merge from NukkiX into here, please remove the temporary plugin from the plugins folder after you update your workspace.

**Comment by joserobjr** [comment]
About `BlockIceFrosted`, I think you can proceed without it's implementation, you just need to check if the ID matches the one registered at `BlockIds`. But I could be wrong.

**Comment by joserobjr** [comment]
I'm going to help you when I wake up

**Comment by joserobjr** [comment]
Vou mesclar quando eu acordar, está difícil escrever, meu remédio de dormir está fazendo efeito e daqui a pouco vou ficar dislexo. melhotr não tentar mesncar coisas aenquyandto euy estiver dislexxiuo

**Comment by joserobjr** [comment]
Awaiting NukkitX#1164 so we can build on a better waterlogging platform

**Comment by Gabriel8579** [comment]
Test: https://youtu.be/DIZynqY5dnQ

**Comment by Gabriel8579** [comment]
It seems that something is wrong when the kelp is at the same height as the water surface: https://youtu.be/wR8EO62CsX8

**Comment by RORIdev** [comment]
Why isn't this merged yet?

**Comment by joserobjr** [comment]
Depending on #204

**Pull request merged**
